delete readline library include

diff --git a/patchgen b/patchgen
--- a/patchgen
+++ b/patchgen
@@ -35,6 +35,8 @@ if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> gcc 9+ compile and link erro
 #cmake setup
 sed -i "s|CMAKE_STATIC_LIBRARY_SUFFIX|CMAKE_SHARED_LIBRARY_SUFFIX|w $_ssc" "$dirb"/src/CMakeLists.txt
 if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: cmake setup 1" && exit 1 ; fi
+sed -i "s|DESERIALIZE -DHAVE_READLINE|DESERIALIZE|w $_ssc" "$dirb"/src/CMakeLists.txt
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: cmake setup 2" && exit 1 ; fi
 
 # logs paths defaulted to tmpfs
 sed -i "s|/var/log/pihole-FTL.log|/run/log/pihole-ftl/pihole-FTL.log|w $_ssc" "$dirb"/src/config.c
