v. 5.3.4 and pid, port and socket setup

diff --git a/patchgen b/patchgen
--- a/patchgen
+++ b/patchgen
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-pkgver=5.3.3
+pkgver=5.3.4
 source="https://github.com/pi-hole/FTL/archive/v$pkgver.tar.gz"
 dira="FTL-$pkgver"
 dirb="$dira.cust"
@@ -40,11 +40,13 @@ if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: cmake setup 1" &&
 sed -i "s|/var/log/pihole-FTL.log|/run/log/pihole-ftl/pihole-FTL.log|w $_ssc" "$dirb"/src/config.c
 if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: logs paths defaulted to tmpfs 1" && exit 1 ; fi
 
-# sock path
+# pid, port and sock default paths
 sed -i "s|/run/pihole/|/run/pihole-ftl/|w $_ssc" "$dirb"/src/config.c
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: sock path 1" && exit 1 ; fi
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: pid, port and sock default paths 1" && exit 1 ; fi
+sed -i "s|/run/pihole-FTL.|/run/pihole-ftl/pihole-FTL.|w $_ssc" "$dirb"/src/config.c
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: pid, port and sock default paths 2" && exit 1 ; fi
 sed -i "s|/run/pihole/|/run/pihole-ftl/|w $_ssc" "$dirb"/tools/socket_client.c
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: sock path 2" && exit 1 ; fi
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: pid, port and sock default paths 3" && exit 1 ; fi
 
 diff -uprN $dira $dirb > arch-ftl-$pkgver.patch
 git add arch-ftl-$pkgver.patch
