no static linking, again

diff --git a/patchgen b/patchgen
--- a/patchgen
+++ b/patchgen
@@ -14,9 +14,12 @@ wget -q -nc $source
 tar xf v$pkgver.tar.gz
 cp -a $dira $dirb
 
-# makefile setup
-sed -i "s|/usr/local/lib|/usr/lib|w $_ssc" "$dirb"/Makefile
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: makefile setup 1" && exit 1 ; fi
+# makefile disable static linking
+sed -n "/^LIBS=-pthread -lrt -Wl,/w $_ssc" "$dirb"/Makefile
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: makefile disable static linking 1" && exit 1 ; fi
+sed -i '/^LIBS=-pthread -lrt -Wl,/d' "$dirb"/Makefile
+sed -i "s|#LIBS=-pthread -lnettle -lgmp -lhogweed|LIBS=-pthread -lnettle -lrt -lgmp -lhogweed|w $_ssc" "$dirb"/Makefile
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: makefile disable static linking 2" && exit 1 ; fi
 
 # git descriptions setup
 sed -i "s|^GIT_BRANCH := .*$|GIT_BRANCH := master|w $_ssc" "$dirb"/Makefile
