nettle 3.5

diff --git a/patchgen b/patchgen
--- a/patchgen
+++ b/patchgen
@@ -14,6 +14,12 @@ wget -q -nc $source
 tar xf v$pkgver.tar.gz
 cp -a $dira $dirb
 
+# nettle 3.5
+sed -i "s|nettle_secp_256r1|nettle_get_secp_256r1|w $_ssc" "$dirb"/dnsmasq/crypto.c
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> nettle 3.5 1" && exit 1 ; fi
+sed -i "s|nettle_secp_384r1|nettle_get_secp_384r1|w $_ssc" "$dirb"/dnsmasq/crypto.c
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> nettle 3.5 2" && exit 1 ; fi
+
 # makefile gcc 9
 sed -i "s|EXTRAWARN=-Werror -Waddress|EXTRAWARN=-Waddress|w $_ssc" "$dirb"/Makefile
 if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> makefile gcc 9 1" && exit 1 ; fi
@@ -35,13 +41,13 @@ if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: git descriptions 
 sed -i "s|^GIT_TAG := .*$|GIT_TAG := v$pkgver|w $_ssc" "$dirb"/Makefile
 if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: git descriptions setup 4" && exit 1 ; fi
 
-# setting up logs paths
+# logs paths defaulted to tmpfs
 sed -i "s|/var/log/pihole-FTL.log|/run/log/pihole-ftl/pihole-FTL.log|w $_ssc" "$dirb"/config.c
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up logs paths 1" && exit 1 ; fi
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: logs paths defaulted to tmpfs 1" && exit 1 ; fi
 sed -i "s|/var/run/pihole-FTL|/run/pihole-ftl/pihole-FTL|w $_ssc" "$dirb"/config.c
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up logs paths 2" && exit 1 ; fi
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: logs paths defaulted to tmpfs 2" && exit 1 ; fi
 sed -i "s|/var/run/pihole/|/run/pihole-ftl/|w $_ssc" "$dirb"/config.c
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up logs paths 3" && exit 1 ; fi
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: logs paths defaulted to tmpfs 3" && exit 1 ; fi
 
 diff -uprN $dira $dirb > arch-ftl-$pkgver.patch
 git add arch-ftl-$pkgver.patch
