v. 6.0

diff --git a/patchgen b/patchgen
--- a/patchgen
+++ b/patchgen
@@ -1,7 +1,7 @@
 #!/bin/sh
 
-pkgver=5.25.2
-pkgrel=2
+pkgver=6.0
+pkgrel=1
 source="https://github.com/pi-hole/FTL/archive/v$pkgver.tar.gz"
 dira="FTL-$pkgver"
 dirb="$dira.cust"
@@ -16,40 +16,46 @@ tar xf v$pkgver.tar.gz
 cp -a $dira $dirb
 
 # git descriptions setup
-sed -i "s|@GIT_BRANCH@|master|w $_ssc" "$dirb"/src/version.h.in
+sed -i "s|@GIT_VERSION@|v$pkgver|w $_ssc" "$dirb"/src/version.c.in
 if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: git descriptions setup 1" && exit 1 ; fi
-sed -i "s|@GIT_VERSION@|v$pkgver|w $_ssc" "$dirb"/src/version.h.in
+sed -i "s|@GIT_DATE@|$(date -I)|w $_ssc" "$dirb"/src/version.c.in
 if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: git descriptions setup 2" && exit 1 ; fi
-sed -i "s|@GIT_DATE@|$(date -I)|w $_ssc" "$dirb"/src/version.h.in
+sed -i "s|@GIT_BRANCH@|master|w $_ssc" "$dirb"/src/version.c.in
 if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: git descriptions setup 3" && exit 1 ; fi
-sed -i "s|@GIT_TAG@|v$pkgver|w $_ssc" "$dirb"/src/version.h.in
+sed -i "s|@GIT_TAG@|v$pkgver|w $_ssc" "$dirb"/src/version.c.in
 if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: git descriptions setup 4" && exit 1 ; fi
-sed -i "s|@GIT_HASH@|builtfromreleasetarball|w $_ssc" "$dirb"/src/version.h.in
+sed -i "s|@GIT_HASH@|builtfromreleasetarball|w $_ssc" "$dirb"/src/version.c.in
 if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: git descriptions setup 5" && exit 1 ; fi
+sed -i "s|@FTL_ARCH@|currentarch|w $_ssc" "$dirb"/src/version.c.in
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: git descriptions setup 6" && exit 1 ; fi
+sed -i "s|@FTL_CC@|currentcompiler|w $_ssc" "$dirb"/src/version.c.in
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: git descriptions setup 7" && exit 1 ; fi
 
 # gcc 9+ compile and link errors, again...
-sed -i "s|EXTRAWARN \"-Werror -Waddress|EXTRAWARN \"-Waddress|w $_ssc" "$dirb"/src/CMakeLists.txt
+sed -i "s|EXTRAWARN_GCC6 \"-Werror|EXTRAWARN_GCC6 \"|w $_ssc" "$dirb"/src/CMakeLists.txt
 if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> gcc 9+ compile and link errors, again... 1" && exit 1 ; fi
 #sed -i "s|relro -fno-common\")|relro -fcommon\")|w $_ssc" "$dirb"/src/CMakeLists.txt
 #if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> gcc 9+ compile and link errors, again... 2" && exit 1 ; fi
 
 #cmake setup
-sed -i "s|CMAKE_STATIC_LIBRARY_SUFFIX|CMAKE_SHARED_LIBRARY_SUFFIX|w $_ssc" "$dirb"/src/CMakeLists.txt
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: cmake setup 1" && exit 1 ; fi
-sed -i "s|DESERIALIZE -DHAVE_READLINE|DESERIALIZE|w $_ssc" "$dirb"/src/CMakeLists.txt
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: cmake setup 2" && exit 1 ; fi
+#sed -i "s|CMAKE_STATIC_LIBRARY_SUFFIX|CMAKE_SHARED_LIBRARY_SUFFIX|w $_ssc" "$dirb"/src/CMakeLists.txt
+#if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: cmake setup 1" && exit 1 ; fi
+#sed -i "s|DESERIALIZE -DHAVE_READLINE|DESERIALIZE|w $_ssc" "$dirb"/src/CMakeLists.txt
+#if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: cmake setup 2" && exit 1 ; fi
 
 # logs paths defaulted to tmpfs
-sed -i "s|/var/log/pihole/FTL.log|/run/log/pihole-ftl/pihole-FTL.log|w $_ssc" "$dirb"/src/config.c
+sed -i "s|/var/log/pihole|/run/log/pihole|w $_ssc" "$dirb"/src/config/config.c
 if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: logs paths defaulted to tmpfs 1" && exit 1 ; fi
+sed -i "s|/var/log/pihole|/run/log/pihole|w $_ssc" "$dirb"/src/config/legacy_reader.c
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: logs paths defaulted to tmpfs 2" && exit 1 ; fi
 
 # pid, port and sock default paths
-sed -i "s|/run/pihole/|/run/pihole-ftl/|w $_ssc" "$dirb"/src/config.c
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: pid, port and sock default paths 1" && exit 1 ; fi
-sed -i "s|/run/pihole-FTL.|/run/pihole-ftl/pihole-FTL.|w $_ssc" "$dirb"/src/config.c
+#sed -i "s|/run/pihole/|/run/pihole-ftl/|w $_ssc" "$dirb"/src/config/config.c
+#if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: pid, port and sock default paths 1" && exit 1 ; fi
+sed -i "s|/run/pihole-FTL.|/run/pihole-ftl/pihole-FTL.|w $_ssc" "$dirb"/src/config/config.c
 if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: pid, port and sock default paths 2" && exit 1 ; fi
-sed -i "s|/run/pihole/|/run/pihole-ftl/|w $_ssc" "$dirb"/tools/socket_client.c
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: pid, port and sock default paths 3" && exit 1 ; fi
+#sed -i "s|/run/pihole/|/run/pihole-ftl/|w $_ssc" "$dirb"/tools/socket_client.c
+#if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: pid, port and sock default paths 3" && exit 1 ; fi
 
 diff -uprN $dira $dirb > arch-ftl-$pkgver-$pkgrel.patch
 git add arch-ftl-$pkgver-$pkgrel.patch
